[package]
name = "flash"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/devnet" }

[addresses]
movectf =  "0x0"
sui = "0x2"
